# The docker-compose DSL syntax format we're using
# 
version: "3.7"
services:
# Database
  db:
    # Define postgres image to use 
    image: postgres
    # Define enviornemt variables
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    # Define volume to allow for persistent data
    volumes:
        - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    # Define internal container port and bind to external localhost port
    # 'external:internal'
    ports:
        - '5433:5432'
  web:
    # Builds server image based on Dockerfile 
    build: ./
    # List containers that the server app is dependent on
    depends_on:
        - db
    # Setting volumes to be able to watch server.js for changes
    volumes:
        - ./app.js:/usr/src/app/app.js
    # Insert envelope file to provide enviornemnt variables
    env_file: ./.env
    # <host-port>:<container-port> to listen to
    ports:
        - "8000:8080"
