

# The docker-compose DSL syntax format we're using

version: "3"


# The containers we want to start and the images to start

# them from

services:
  #
  #Base postgres 9.6 image that we can connect to. This
  #will get downloaded straightfrom Docker Hub when we 
  #bring up our containers
  #
  #postgres:
   # image: postgres:9.6
    #restart: always
    #ports:
    # - "5432:5432"
    #volumes:
     #- .:/data

  # our basic node server we'll name "basic"

  gcma-api: 

    # the directory path - relative to this compose file - where

    # we'll be able to find the Dockerfile

    build: ./

    # containers api will depend on 
    #depends_on:
      #-postgres

    #defines enviornment
    enviornment:
      

    # the port mappings we do so that traffic that docker

    # will forward from localhost -> container

    ports:

      - "8080:8000"
